#!/usr/bin/env python
import sys, argparse
from xtermcolor.ColorMap import (
    TrueColorMap,
    XTermColorMap,
    VT100ColorMap,
    NoneColorizer,
)


def cPrintfString(xterm):
    return '"\\x1b[38;5;{xterm:d}m%s\\x1b[0m"'.format(xterm=xterm)  # ]]


def Cli():
    parser = argparse.ArgumentParser(
            description='xtermcolor: 256 terminal color library')

    parser.add_argument('action',
                        choices=['convert', 'list'],
                        help='Actions')

    parser.add_argument('--color',
                        help='Color to convert')

    parser.add_argument('--compat',
                        choices=['xterm', 'vt100'],
                        default='xterm',
                        help='Compatibility mode.  Defaults to xterm.')

    cli = parser.parse_args()

    colorMap = NoneColorizer()

    if TrueColorMap.check_support(1):
        colorMap = TrueColorMap()
    elif cli.compat.lower().startswith('xterm'):
        colorMap = XTermColorMap()
    elif cli.compat.lower() == 'vt100':
        colorMap = VT100ColorMap()

    if cli.compat.lower() not in ['xterm', 'vt100']:
        sys.stderr.write('Error: --compat must be xterm or vt100\n')
        sys.exit(-1)

    if cli.action == 'list':
        for xterm, hexcolor in colorMap.getColors().items():
            string = "\x1b[38;5;{xterm:d}mansi={xterm:d}; rgb=#{hexcolor:06x}; printf={cprintf:s}\x1b[0m"    # ]]
            print(string.format(xterm=xterm, hexcolor=hexcolor, cprintf=cPrintfString(xterm)));

    if cli.action == 'convert':
        if not cli.color:
            sys.stderr.write('Error: must specify --color\n')
            sys.exit(-1)
        if cli.color[0] == '#':
            cli.color = '0x' + cli.color[1:]
        cli.color = int(cli.color, 16)

        colorizedMsg = colorMap.colorize('The quick brown fox jumped over the lazy dog.', cli.color)
        (ansi, rgb) = colorMap.convert(cli.color)
        print("#{start:06x} is closest to #{closest:06x} which is ANSI code {ansi:d}\n".format( \
                start=cli.color, closest=rgb, ansi=ansi))
        print("Example: " + colorizedMsg)
        print("printf() string: " + cPrintfString(ansi))


if __name__=='__main__':
    Cli()
